# Generated by Django 5.1.5 on 2025-01-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_song_duration_alter_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_files_songs'),
        ),
    ]
