# Generated by Django 5.1.5 on 2025-02-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_song_photo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers')),
            ],
            options={
                'verbose_name': 'РЕЛИЗЫ',
                'verbose_name_plural': 'РЕЛИЗЫ',
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'АЛЬБОМЫ', 'verbose_name_plural': 'АЛЬБОМЫ'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'ПЕСНИ', 'verbose_name_plural': 'ПЕСНИ'},
        ),
        migrations.CreateModel(
            name='SongRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='song_files_release')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_files_release')),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to='photo_files_songs_release')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_releases', to='webapp.release')),
            ],
            options={
                'verbose_name': 'РЕЛИЗ ПЕСНИ',
                'verbose_name_plural': 'РЕЛИЗ ПЕСНИ',
            },
        ),
    ]
