# Generated by Django 5.1.5 on 2025-02-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_release_alter_album_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrelease',
            old_name='album',
            new_name='release',
        ),
    ]
