# Generated by Django 5.1.5 on 2025-02-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_album_songrelease_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrelease',
            old_name='audio_file',
            new_name='audio_file_release',
        ),
        migrations.RenameField(
            model_name='songrelease',
            old_name='photo_file',
            new_name='photo_file_release',
        ),
        migrations.RenameField(
            model_name='songrelease',
            old_name='video_file',
            new_name='video_file_release',
        ),
    ]
